// Code generated by ent, DO NOT EDIT.

package blog

const (
	// Label holds the string label denoting the blog type in the database.
	Label = "blog"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldBlogId holds the string denoting the blogid field in the database.
	FieldBlogId = "blog_id"
	// FieldBlogTitle holds the string denoting the blogtitle field in the database.
	FieldBlogTitle = "blog_title"
	// FieldBlogContent holds the string denoting the blogcontent field in the database.
	FieldBlogContent = "blog_content"
	// Table holds the table name of the blog in the database.
	Table = "blogs"
)

// Columns holds all SQL columns for blog fields.
var Columns = []string{
	FieldID,
	FieldBlogId,
	FieldBlogTitle,
	FieldBlogContent,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
